### ISSUE TITLE
Tabs - Content Property does not work for HTMLElement

### ISSUE THREAD

**Issue by jchilde** [syncfusion/ej2-react-navigations#2]
1. Trying to create a tabbed form.  Need to put fields in it.  The TabItemDirective content property appears to only work for text.  I am using your Wizard demo as a go by.  Of course, the Wizard demo doesn't appear to work (using Chrome).

In the wizard, you enter '#id' in the content section.   Here is my code:
`     
       <form onSubmit={this._handleSubmit} >
        <TabComponent heightAdjustMode="Auto" >
          <TabItemsDirective>
            <TabItemDirective header={{ text: "a" }} content={'#testElement'} />
            <TabItemDirective header={{ text: "b" }} content={"B"} />
          </TabItemsDirective>
        </TabComponent>
        <div id="testElement" style={{ display: "none" }}>ccccc</div>
      </form>
`

2.  Can you adjust this package to allow a JSX.Element to be used as content for a tab or allow JSX as a sub element like below:

`
<TabItemDirective header={{ text: "MyHeader" }} />
       <div>Something Here</div>
</TabItemDirective>
`

**Comment by SharpEzhil** [comment]
Hi @jchilde ,

**Query 1: “Trying to create a tabbed form. Need to put fields in it. The TabItemDirective content property appears to only work for text. I am using your Wizard demo as a go by. Of course, the Wizard demo doesn't appear to work (using Chrome). In the wizard, you enter '#id' in the content section.”**
Tab wizard sample works fine in Chrome browser. Check the react sample link https://ej2.syncfusion.com/16.1.24/react/demos/#/material/tab/wizard . Can you share the version of chrome you are using so that we can validate with version specific ?
We have prepared sample based on the code shared and TabItemDirective’s content property work for HTML elements also. Find the demo sample, https://plnkr.co/edit/jJtgYMZmtLAM6VNUPvFa?p=preview 

**Query 2: “Can you adjust this package to allow a JSX.Element to be used as content for a tab or allow JSX as a sub element like below”**
Currently we don’t have support for using React element within child directives.  So we have added in our feature request list. And we will include this feature in our Volume 2, 2018 release.

Regards,
Ezhil S
